pubspec.yaml
Now that we're verified, this fixes #1.
=> Improve pubspec

ios/Classes/AblyStreamsChannel.m
Dropping key from streams dict while enumerating - [err: Collection was mutated while being enumerated]
Fixed by using a `mutableCopy` of `_streams`
=> Fix: iOS hot-restart issue with active listeners

DeveloperNotes.md, README.md, android/src/main/java/io/ably/flutter/plugin/AblyEventStreamHandler.java, android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java, android/src/main/java/io/ably/flutter/plugin/generated/PlatformConstants.java, bin/codegencontext.dart, example/.gitignore, example/lib/main.dart, example/test_harness/.gitignore, example/test_harness/package-lock.json, example/test_harness/package.json, example/test_harness/publish.js, ios/Classes/AblyFlutterStreamHandler.m, ios/Classes/codec/AblyFlutterWriter.m, ios/Classes/codec/AblyPlatformConstants.h, ios/Classes/codec/AblyPlatformConstants.m, lib/src/codec.dart, lib/src/generated/platformconstants.dart, lib/src/impl/realtime/channels.dart, lib/src/impl/realtime/connection.dart, lib/src/spec/message.dart, lib/src/spec/realtime/channels.dart
Listening to messages on a Realtime Channel
This implementation follows dart idiomatic approach
```dart
Stream<ably.Message> messageStream = channel.subscribe();
StreamSubscription<ably.Message> channelMessageSubscription = messageStream.listen((ably.Message message){
print("New message arrived ${message.data}");
});
```
```dart
await channelMessageSubscription.cancel();
```
=> Realtime message subscription

example/ios/Podfile, example/ios/Podfile.lock, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner/AppDelegate.h, example/ios/Runner/main.m, example/pubspec.lock, ios/Classes/AblyFlutterStreamHandler.m, ios/Classes/codec/AblyFlutterReader.h, ios/Classes/codec/AblyFlutterReader.m, ios/Classes/codec/AblyFlutterWriter.m, ios/ably_flutter_plugin.podspec
At https://github.com/ably/ably-flutter/pull/46/commits/72c575ae8602c24afa26291c3c311e80e6f1cb37 this branch sorts out failing `flutter run` for iOS in my test project locally. The test project's `pubspec.yaml` looks like this (with the majority of comments removed for brevity):
```
name: ably_flutter_from_github
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
sdk: ">=2.7.0 <3.0.0"
dependencies:
flutter:
sdk: flutter
ably_flutter_plugin:
git:
url: https://github.com/ably/ably-flutter.git
ref: feature/ios-podspec-20200915
cupertino_icons: ^0.1.3
dev_dependencies:
flutter_test:
sdk: flutter
flutter:
uses-material-design: true
```
=> iOS podspec tweaks

analysis_options.yaml
I checked https://dart-lang.github.io/linter/lints/ for new linter rules and added them.
Most of the new ones are still commented out because they are not yet available in stable Dart.
I also cleaned up formatting and comments a bit.
If some of the enabled lints are not supported yet in the Dart version you are using, please just comment them out with a comment that it's not yet available.
=> Update with newest lints and clean up formatting and comments

android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java, android/src/main/java/io/ably/flutter/plugin/generated/PlatformConstants.java, bin/codegencontext.dart, example/test_harness/tokenRequest.js, ios/Classes/AblyFlutter.m, ios/Classes/codec/AblyFlutterReader.m, ios/Classes/codec/AblyPlatformConstants.h, ios/Classes/codec/AblyPlatformConstants.m, lib/src/codec.dart, lib/src/generated/platformconstants.dart, lib/src/impl/platform_object.dart, lib/src/impl/realtime/channels.dart, lib/src/impl/realtime/connection.dart, lib/src/impl/realtime/realtime.dart, lib/src/impl/rest/channels.dart, lib/src/impl/rest/rest.dart, lib/src/method_call_handler.dart, lib/src/spec/constants.dart, lib/src/spec/realtime/realtime.dart, test/realtime/channel_test.dart, test/rest/channel_test.dart, test_integration/lib/test/realtime_publish_test.dart, test_integration/lib/test/realtime_publish_with_auth_callback_test.dart, test_integration/lib/test/test_factory.dart, test_integration/lib/test/test_names.dart, test_integration/test_driver/test_implementation/realtime_tests.dart, test_integration/test_driver/tests_config.dart
Support for `authCallback` Realtime operations
**Android**
**iOS**
1. Realtime instance will be created with `authCallback` in `ClientOptions`
2. `Realtime#connect` will be triggered from user code
3. ably library code calls a proxy `authCallback` on platform code and that will immediately return `null`, but will make a MethodChannel call (with name `realtimeAuthCallback`) to dart side for token data.
4. dart side receives the `MethodChannel` call and triggers authCallback to return the value to platform code.
platform code will set this response token data in temporary storage.
5. Trigger from `#2` will receive an error with code `80019` which will suppress the error and will check a boolean on dart side if the authentication update was complete and then retry publishing again.
6. Now, …
=> realtime authcallback

.run/example.run.xml, .run/integration_test.run.xml, README.md, android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java, android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java, android/src/main/java/io/ably/flutter/plugin/generated/PlatformConstants.java, bin/codegencontext.dart, example/lib/main.dart, example/pubspec.yaml, example/test_harness/tokenRequest.js, ios/Classes/AblyFlutterPlugin.m, ios/Classes/codec/AblyFlutterReader.m, ios/Classes/codec/AblyFlutterWriter.m, ios/Classes/codec/AblyPlatformConstants.h, ios/Classes/codec/AblyPlatformConstants.m, lib/src/codec.dart, lib/src/generated/platformconstants.dart, lib/src/impl/realtime/channels.dart, lib/src/impl/rest/channels.dart, lib/src/impl/rest/presence.dart, lib/src/method_call_handler.dart, lib/src/spec/common.dart, lib/src/spec/message.dart, lib/src/spec/rest/channels.dart, test/models/presence_message_test.dart, test_integration/pubspec.yaml
getting presence members via `rest#channels#channel#presence#get` list as a `PaginatedResult`
Supported platforms:
Example:
```dart
void getPresence([ably.RestPresenceParams params]) async {
// getting channel history, by passing or omitting the optional params
var result = await channel.presence.get(params);
var presenceMembers = result.items; //returns PresenceMessages
var hasNextPage = result.hasNext(); //tells whether there are more results
if(hasNextPage){    
result = await result.next();  //fetches next page results
presenceMembers = result.items;
}
if(!hasNextPage){
result = await result.first();  //fetches first page results
presenceMembers = result.items;
}
}
// getting presence members with default params
getPresence();
// filtered presence members …
```
=> Rest Channel Presence#get

.github/workflows/docs.yml
I was just starting some work on this repository and realised I had this commit locally but yet to be pushed.
@owenpearson is currently working on an action that will replace most of this, but I still thought it worthwhile to get this improvement uploaded in lieu.
Copied over from https://github.com/ably/ably-asset-tracking-android/pull/283.
=> Replace hard-coded repository URL components

CHANGELOG.md, pubspec.yaml
I did a publication dry run before I pushed this branch up which is why there's [an extra commit](https://github.com/ably/ably-flutter/commit/88414c298d3cc3ac2c4ba7240bd207d8c2d5dd4a).
Once this pull request lands then I shall:
1. Create and push the `1.2.0-preview.2` tag
2. Publish to pub.dev
3. Create release with "Pre-release" attribution, per [1.2.0, Preview 1](https://github.com/ably/ably-flutter/releases/tag/1.2.0-preview.1)
=> Preview Release - 1.2.0 preview.2

android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java
Use latch to turn asynchronous method channel call synchronous. Please see https://github.com/ably/ably-flutter/issues/156 to see the exception which is thrown at **every launch of the app** when token authentication callback is first called by ably-java.
Closes https://github.com/ably/ably-flutter/issues/156
=> Fix `invalid authCallback response` when using token authentication

lib/src/common/src/backwards_compatibility.dart, lib/src/platform/src/realtime/realtime.dart, lib/src/platform/src/realtime/realtime_channel.dart, lib/src/platform/src/rest/rest_channel.dart, test/realtime/channel_test.dart, test/rest/channel_test.dart
A customer has asked us to add support for Flutter 2.2.3 to avoid them upgrading to Flutter 2.5 in a [slack message](https://ably-real-time.slack.com/archives/C0178QGC093/p1635945748037800). Unfortunately, currently, we are using `unawaited` introduced in Dart 2.14, which is first available in Flutter 2.5.0. 
As a solution, we copied the 1 line of implementation into this SDK, and import this instead.
We are also planning to add tests using older Flutter versions in CI to avoid this problem in the future, but there are some challenges in doing so, which we will tackle in a separate (currently draft) PR: https://github.com/ably/ably-flutter/pull/197
=> Copy unawaited implementation into Ably Flutter to fix build failures for Flutter 2.2.3

example/lib/main.dart, example/pubspec.lock
With this change, users of the example app no longer need to create instances of Realtime and Rest. These get created automatically. This simplifies the state for the entire app, as the rest of the app can rely on Realtime and Rest instances existing. This allows me to avoid adding more complicated state management tools, like Bloc, getx, provider, etc for my upcoming symmetric encryption PR.
The UI changes from (before, left) and after (right):
=> Simplify state in example app

lib/src/platform/platform_internal.dart, lib/src/platform/src/publish_queue_item.dart, lib/src/platform/src/realtime/realtime_channel.dart, lib/src/platform/src/rest/rest_channel.dart
This is a small fix, there was duplicate class, and I'm just deleting one. The file being referenced instead is https://github.com/ably/ably-flutter/blob/main/lib/src/platform/src/rest/publish_queue_item.dart
=> Remove a duplicate class and use the other one instead

example/lib/push_notifications/android_push_notification_configuration.dart, example/pubspec.lock, example/pubspec.yaml
We must update `flutter_local_notifications` to allow builds to succeed. The version we currently use uses bintray, and it was not working today as per our own experiences trying to download dependencies on @ikbalkaya's machine, and https://www.reddit.com/r/devops/comments/qq3bd9/gradle_ci_fails_because_jcenterbintray_is_down/. 
I also took this opportunity to update `device_info_plus`.
=> Update `flutter_local_notifications` to avoid bintray dependency resolution error

android/src/main/java/io/ably/flutter/plugin/push/FirebaseMessagingReceiver.java, android/src/main/java/io/ably/flutter/plugin/push/PushMessagingEventHandlers.java, example/lib/main.dart
When the app receives multiple push notifications, a crash occurs. This is because the broadcast receiver is not unregistered. In this fix, I refactor the code slightly, whilst making sure to unregister the receiver.
I also noticed the Rest client did not have a clientId set, so I did that here too instead of creating an entirely new PR.
=> Fix app crashing when receiving multiple push notifications

ios/Classes/handlers/PushActivationEventHandlers.swift
This PR fixes the success and error handling for push. Its handling push activation (`didActivateAblyPush`, deactivation `didDeactivateAblyPush` and update `didAblyPushRegistrationFail ` success/error given by Ably Cocoa.
In some cases, an error would be caused because we try to send a `FlutterError` through a `MethodChannel`. This is not a type that can be serialized through a `MethodChannel`. Instead, this fix uses the `ARTErrorInfo`, which has been used elsewhere to send back errors to platform side. It also avoids extraneous logic: mostly passing the errorInfo given by Ably Cocoa to the dart side. 
TLDR: Removing complexity and just passing errors (or `nil`) directly.
=> Handle error cases on iOS correctly, and simplify code

lib/src/authentication/src/client_options.dart, lib/src/platform/src/codec.dart, lib/src/platform/src/realtime/realtime.dart
It is nice to avoid optionals, and to be NNBD: non null by default. In this PR, I set the default values and make fields non-optional. 
Closes https://github.com/ably/ably-flutter/issues/230
=> Add default values to ClientOptions

example/lib/main.dart
In this UI enhancement, I hide the API secret key from the API key string. This allows me to show the example app to more people without worrying that I am leaking API keys. This should allow other users to share screenshots more safely too:
I also replaced the Text widget with I previously created called `TextRow`, so it now the labels are in blue:
This is the same widget used when receiving push messages or encrypted messages:
=> Hide API key secret inside API key UI

example/lib/main.dart, example/lib/ui/system_details_sliver.dart
The example app UI remains the same. In this PR, I refactor the system details section you see below into a separate widget.
=> Example app: Extract System Details sliver into new widget

test/mock_method_call_manager.dart
Following https://docs.flutter.dev/release/breaking-changes/mock-platform-channels to remove deprecated method calls.
Specifically: 
> Code that does not have access to a WidgetTester can refer to TestDefaultBinaryMessengerBinding.instance!.defaultBinaryMessenger instead of tester.binding.defaultBinaryMessenger.
=> Replace deprecated method calls in tests

PushNotifications.md, example/ios/Runner/AppDelegate.m, ios/Classes/AblyFlutter.h, ios/Classes/AblyFlutter.m, ios/Classes/AblyInstanceStore.h, ios/Classes/AblyInstanceStore.m, ios/Classes/handlers/PushHandlers.swift
This PR does 2 things:
- It fixes https://github.com/ably/ably-flutter/issues/276
- It allows users to give Ably flutter the device token if they're having issues activating push with Ably. This happens because in some cases (e.g. a customer), `didRegisterForRemoteNotifications` does not get called in Ably Flutter when running on iOS. This might happen due to method swizzling by other dependencies. This is a **workaround** for users who cannot fix the fact `didRegisterForRemoteNotifications` is not being called in Ably Flutter.
=> Send deviceToken to Ably clients which already have been instantiated

android/src/main/java/io/ably/flutter/plugin/push/FirebaseMessagingReceiver.java
This issue is a workaround that fixes ANR by moving blocking operations to a background threads.
* Moves `sendMessageToFlutterApplication` to a background thread
=> Fix anr issue

example/ios/Podfile.lock, ios/ably_flutter.podspec, test_integration/ios/Podfile.lock
This involved (some steps may have not been required):
1. Modifying version in `ios/ably_flutter.podspec`
2. `flutter clean` from root
3. `flutter pub get` from root
4. `flutter pub get` from `example/`
5. `flutter pub get` from `test_integration/`
6. `pod repo update`
7. `pod update Ably && pod install` from `example/ios`, updating `Podfile.lock` in that folder
8. `pod update Ably && pod install` from `test_integration/ios`, updating `Podfile.lock` in that folder
Fixes #287
=> Update to `ably-cocoa` v.1.2.8

PushNotifications.md
A customer was facing issues with activating and deactivating their device. After investigation, it turned out they had activated the device previously on  a different environment.
See this internal slack discussion about long term improvements we can make to developer experience to help customers avoid making this issue in the first place: https://ably-real-time.slack.com/archives/CSQEKCE81/p1638354865280100
=> Add documentation about actions required to make Ably Flutter push work across multiple environments

example/ios/Podfile.lock, ios/ably_flutter.podspec, test_integration/ios/Podfile.lock
Fixes #296.
There were complications when I worked on this locally, though broadly I was following the procedure described here: https://github.com/ably/ably-flutter/pull/293
=> Update to `ably-cocoa` v.1.2.9

example/ios/Podfile.lock, ios/ably_flutter.podspec, test_integration/ios/Podfile.lock
The experience of updating this dependency was even worse this time, than [before](https://github.com/ably/ably-flutter/pull/299), and definitely not as easy as [the time before that](https://github.com/ably/ably-flutter/pull/293).
So many layers of tooling. This time I ended up doing `gem update` and also reinstall of `cocoapods` gem. That may have solved it. Not sure, honestly. The pernicious error I kept getting was:
```
ios % pod update Ably
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Ably":
In Podfile:
ably_flutter (from `.symlinks/plugins/ably_flutter/ios`) was resolved to 1.2.10, which depends on
Ably (= 1.2.10)
None of your spec sources contain a spec satisfying the dependency: `Ably (= 1.2.10)`.
You have …
```
=> Update to `ably-cocoa` v.1.2.10.

UPDATING.md
It incorrectly inferred that `activationEvents` was renamed to `pushEvents` in a version earlier than the change was actually made in.
Spotted for us by a customer, see this [internal Slack message](https://ably-real-time.slack.com/archives/C012DA29VM0/p1642757125051200?thread_ts=1642401386.021100&cid=C012DA29VM0).
=> Correct the migration guide.

PushNotifications.md, README.md
This PR adds a warning for users who use Firebase messaging library along with Ably library
=> Add workaround for firebase messaging

.gitignore, .vscode/launch.json, README.md
I've noticed that example app requirements aren't complete, so I did a few changes to make running ample app easier:
* Added a missing `launch.json` file. It was mentioned in the docs, but it wasn't commited, most probably because of gitignore covering the whole `vscode` folder
* Added a short note about Firebase instance configuration being required for Android builds. If there's no configuration file in the reposiotry, building the sample app fails, so I think it's worth to have that information in readme file
=> Readme enchancements for example app

example/android/app/build.gradle, example/android/app/src/main/AndroidManifest.xml, example/android/app/src/main/res/values/styles.xml, example/android/build.gradle, example/pubspec.lock, example/pubspec.yaml, pubspec.lock, pubspec.yaml, test_integration/android/app/build.gradle, test_integration/android/app/src/main/AndroidManifest.xml, test_integration/android/build.gradle
This PR is a migration supposed to solve #311, by fully adapting Flutter Android Embedding V2 following the [official migration guide](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects). Besides the migration itself, additional compatibility changes include:
* Forced Kotlin version for example app (Flutter recommends setting 1.5.31)
* Changed Android target and compile SDK versions to latest (32)
* Updated a few Flutter dependencies for example app
* Updated test dependency version for dart library
* Set Android application as exported in Manifest file, to comply with Android S requirements
=> Android embedding v2

ios/Classes/codec/AblyFlutterWriter.m, lib/src/platform/src/codec.dart, lib/src/realtime/src/channel_state_event.dart
This is supposed to fix bug #297, the original fix was issued on #270 but I don't think the approach there was correct, so I changed a few things.
The issue was caused by this definition of Obj-C macro:
```objc
#define WRITE_VALUE(DICTIONARY, JSON_KEY, VALUE) { 
if (VALUE) {
[DICTIONARY setObject:VALUE forKey:JSON_KEY];
} 
}
```
which is supposed to write JSON key only if `VALUE` parameter is not `nil`. By accident, if the parameter is not `nil`, but it happens to be `0` or any other falsey value, the key also isn't written 😆  I've updated the base method to only check for `nil` and also write `false` values.
The other error was with tenary operators and booleans. The expression:
```objc
[stateChange resumed]?@([stateChange resumed]):nil
```
evaluates to `nil` if `resumed` is `nil` or …
=> Channel resumed parameter now has to be non-null

android/src/main/java/io/ably/flutter/plugin/AblyInstanceStore.java, android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java
=> `AblyInstanceStore` concurrency

android/src/main/java/io/ably/flutter/plugin/AblyFlutter.java, android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java, android/src/main/java/io/ably/flutter/plugin/push/PushActivationEventHandlers.java, android/src/main/java/io/ably/flutter/plugin/push/PushActivationReceiver.java
This PR fixes **activation handling** code by 
* Fixes some issues with `PushActivationHandlers` singleton, by providing an instance method and converting some static methods into instance methods
* Moves activation broadcast receiver to a separate file, creating methods for registering with callback and unregistering.
* Respects the FlutterEngine lifecycle by registering the receiver when it's attached to engine and deregisters it when it's detached. 
Closes https://github.com/ably/ably-flutter/issues/304
Please note that changes here won't cause a manual application launch, meaning that any message from broadcast receiver will be received only when the Flutter engine is attached. I did this to prevent further bugs raising from inconsistencies related to Flutter engine lifecycle. …
=> Separate activation broadcast receiver from channel handler class

.github/workflows/check.yaml, .github/workflows/docs.yml, .github/workflows/flutter_integration.yaml
Closes #325 and closes #317 , and additionally updates `flutter-action` step version to `2`. This should greatly reduce the CI runtime by reducing the number of components downloaded with each run
=> Simplified GitHub actions flow

test_integration/lib/config/test_constants.dart, test_integration/lib/config/test_factory.dart, test_integration/lib/config/test_names.dart, test_integration/lib/test/realtime/realtime_encrypted_publish_test.dart, test_integration/lib/test/rest/rest_encrypted_publish_test.dart, test_integration/test_driver/test_implementation/realtime_tests.dart, test_integration/test_driver/test_implementation/rest_tests.dart, test_integration/test_driver/tests_config.dart
This should close #302 and probably also #205. I've added integration tests for:
* Publishing to encrypted REST channel
* Publishing to encrypted realtime channel
* Spec requirements for publishing on encrypted REST channel
These tests should help us catch any issues with encryption implementation for channels, like #296. I did not include spec requirements for publishing realtime channel, because currently there are no spec tests for realtime channels, so I'd need to create them first, before testing the encrypted version. I've created a separate issue for this: #332.
=> Encrypted channels integration testing

.github/workflows/flutter_integration.yaml
This is related to #232 but I'm not sure if it will solve the problem entirely. So I'm not closing the issue for now and I'll watch the CI for a while to see if the errors still occur.
Besides switching from `macos` runner to `ubuntu` I've also added a few additional params to the virtual machine (copy/paste from [`ably/java`'s integration test config](https://github.com/ably/ably-java/blob/main/.github/workflows/emulate.yml) but it should be fine for our use case).
=> Switched CI integration tests to run on ubuntu instead of macos

android/src/main/java/io/ably/flutter/plugin/AblyEventStreamHandler.java, android/src/main/java/io/ably/flutter/plugin/AblyFlutter.java, android/src/main/java/io/ably/flutter/plugin/BackgroundMethodCallHandler.java, android/src/main/java/io/ably/flutter/plugin/StreamsChannel.java, android/src/main/java/io/ably/flutter/plugin/push/FirebaseMessagingReceiver.java, android/src/main/java/io/ably/flutter/plugin/push/ManualFlutterApplicationRunner.java, android/src/main/java/io/ably/flutter/plugin/push/PushActivationEventHandlers.java, android/src/main/java/io/ably/flutter/plugin/push/PushMessagingEventHandlers.java, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/ios/Runner/AppDelegate.swift, example/lib/ui/ably_service.dart, ios/Classes/AblyFlutter.m, ios/Classes/handlers/PushActivationEventHandlers.swift, lib/src/authentication/src/client_options.dart, lib/src/logging/logging.dart, lib/src/logging/src/log_handler.dart, test/models/client_options.dart, test_integration/lib/test/realtime/realtime_history_test.dart, test_integration/lib/test/realtime/realtime_presence_enter_update_leave.dart, test_integration/lib/test/realtime/realtime_presence_get.dart, test_integration/lib/test/realtime/realtime_presence_history_test.dart, test_integration/lib/test/realtime/realtime_presence_subscribe.dart, test_integration/lib/test/realtime/realtime_publish_test.dart, test_integration/lib/test/realtime/realtime_time_test.dart, test_integration/lib/test/rest/rest_history_test.dart, test_integration/lib/test/rest/rest_presence_get_test.dart, test_integration/lib/test/rest/rest_presence_history_test.dart, test_integration/lib/test/rest/rest_publish_test.dart, test_integration/lib/test/rest/rest_time_test.dart
This should resolve #238, although it does not use the mentioned `LogHandler`. Instead, the changes contain:
* Removing the `LogHandler` entirely from Dart code
* Replacing Android native logging with `Log` implementation from `ably-java`. Luckily, their implementation is the same so it was only a matter of imports
* Replacing ios `print` and `NSLog` calls with `ARTLog` implementation from `ably-cocoa`. This was not possible everywhere, because unlike `Log` from `ably-java` the `ARTLog` isn't a singleton, so I only updated a few places
With these changes, most of the logging from Android and iOS platform native code should respect logging level set in Ably `ClientOptions`.
=> LogHandler removal & logging improvements

test_integration/lib/config/test_factory.dart, test_integration/lib/config/test_names.dart, test_integration/lib/test/realtime/realtime_encrypted_publish_test.dart, test_integration/lib/test/realtime/realtime_publish_test.dart, test_integration/lib/test/rest/rest_encrypted_publish_test.dart, test_integration/test_driver/test_implementation/realtime_tests.dart, test_integration/test_driver/test_implementation/rest_tests.dart, test_integration/test_driver/tests_config.dart
This PR should close #332 and together with that, resolve #205 (I decided to implement them both at the same time, since they're strongly related). The changes include:
* A copy of REST channel publish spec test for real-time channels. The copy is not 1:1, since real-time channels have a few differences according to spec. [RTL6a1](https://docs.ably.com/client-lib-development-guide/features/#RTL6a1) indicates test components that were removed because they are present in REST channels, but not in real-time channels.
* A new test set for encrypted real-time publish spec [RSL5](https://docs.ably.com/client-lib-development-guide/features/#RSL5). I've followed the suggestion that @ikbalkaya gave me and utilized the channel history method to verify that messages are encrypted and decrypted …
=> Realtime channel integration tests

PushNotifications.md, README.md, example/android/app/src/google-services.json, example/lib/ui/push_notifications/push_notifications_activation_sliver.dart, example/lib/ui/push_notifications/push_notifications_subscriptions_sliver.dart
This should resolve https://github.com/ably/ably-flutter/issues/318 and make the sample app work without any additional configuration. It;s based on `feature/example-app/provisioning` because they both alter sample application and readme files and I wanted to avoid conflicts.
The most important change is the dummy `google-services.json` file. I've decided to use this approach, since it seemed to be the most reasonable one. File structure is compliant with Firebase requirements, but it doesn't contain any data inside. This is just enough to run the app, as long as no Firebase services are needed. 
Google states that these files do not contain any sensitive information, but I'm not a fan of putting any server instance data or API keys inside the repository. In our use case, it doesn't …
=> Sample app default google-services file

CHANGELOG.md, README.md, example/lib/ui/ably_service.dart, lib/src/authentication/src/auth_options.dart, lib/src/authentication/src/client_options.dart, lib/src/platform/src/codec.dart, lib/src/platform/src/realtime/realtime.dart, lib/src/platform/src/rest/rest.dart, test/ably_flutter_plugin_test.dart, test/realtime/channel_test.dart, test/rest/channel_test.dart, test_integration/lib/test/realtime/realtime_encrypted_publish_test.dart, test_integration/lib/test/realtime/realtime_events_test.dart, test_integration/lib/test/realtime/realtime_history_test.dart, test_integration/lib/test/realtime/realtime_presence_enter_update_leave.dart, test_integration/lib/test/realtime/realtime_presence_get.dart, test_integration/lib/test/realtime/realtime_presence_history_test.dart, test_integration/lib/test/realtime/realtime_presence_subscribe.dart, test_integration/lib/test/realtime/realtime_publish_test.dart, test_integration/lib/test/realtime/realtime_publish_with_auth_callback_test.dart, test_integration/lib/test/realtime/realtime_subscribe.dart, test_integration/lib/test/realtime/realtime_time_test.dart, test_integration/lib/test/rest/rest_capability_test.dart, test_integration/lib/test/rest/rest_encrypted_publish_test.dart, test_integration/lib/test/rest/rest_history_test.dart, test_integration/lib/test/rest/rest_presence_get_test.dart, test_integration/lib/test/rest/rest_presence_history_test.dart, test_integration/lib/test/rest/rest_publish_test.dart, test_integration/lib/test/rest/rest_publish_with_auth_callback_test.dart, test_integration/lib/test/rest/rest_time_test.dart
This is a part of #61, including changes only for `ClientOptions` and `AuthOptions`, without moving the fields as private. Main changes:
* Updated constructor of `AuthOptions` and `ClientOptions` to use named parameters
* Deprecated `fromKey` methods, since the object can be now created with constructor invocation
* Refactored all places where `ClientOptions` was created with public parameter setters 
Although this PR is fairly large, most of the changes were done in integration testing, and none of the changes are breaking in any way - users should be able to migrate without any issues. Moving the variables as private is a breaking change, so I decided to implement this later, in a separate PR, to give users some more time to adopt these changes before we deprecate the public fields
=> Refactor of ClientOptions

android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java, android/src/main/java/io/ably/flutter/plugin/generated/PlatformConstants.java, bin/codegen_context.dart, example/lib/push_notifications/push_notification_service.dart, example/lib/ui/push_notifications/push_notifications_activation_sliver.dart, ios/Classes/codec/AblyPlatformConstants.h, ios/Classes/codec/AblyPlatformConstants.m, lib/src/generated/platform_constants.dart, lib/src/push_notifications/src/push.dart
This PR adds an experimental method `Push.reset()` that clears the state of `ActivationStateMachine` for Push Notifications. This method can be used to solve some issues with activating push devices in Ably service, but since it's an experimental solution it shouldn't be used without a good reason.
Internally, the `reset()` method call clears `SharedPreference` storage and restores `ActivationStateMachine` to its initial state, removing all local device data and making it possible to perform a clean activation of device.
=> Experimental method to reset push device on Android

android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java
This should resolved #356. I'm not sure why those values were cast to `int` in the first place, since `TokenDetails` in `ably-java` uses `long` internally for storing them, but I think this should resolve the issue
=> Updated Android message codec to use long values for TokenDetails

UPDATING.md, lib/src/authentication/src/token_details.dart, lib/src/authentication/src/token_params.dart, lib/src/authentication/src/token_request.dart, lib/src/platform/src/codec.dart
This is another part of https://github.com/ably/ably-flutter/issues/61, continuing work from #348, but this time in scope of token-related classes instead of client options. Main changes include:
* `Codec` class was updated to use constructors instead of public fields for `TokenDetails` and `TokenParams`
* `TokenDetails`, `TokenParams` and `TokenRequest` classes were made `@immutable`, and their public fields `final`. This pattern is already present in some files in the codebase and I think for classes like this it may be the best approach - after the object is created, it can't be changed by reassigning the public fields.
* The changes to public fields are breaking changes, but I don't think they will have a large impact, because constructors for these classes were added quite a while …
=> Named parameters and immutable fields for token classes

lib/src/platform/src/codec.dart, lib/src/realtime/src/channel_state_event.dart, lib/src/realtime/src/connection_state_change.dart, lib/src/realtime/src/realtime_channel_options.dart, lib/src/realtime/src/realtime_history_params.dart, lib/src/realtime/src/realtime_presence_params.dart
I'm continuing my journey trough #61, this time for all `realtime` components. This time changes include:
* Making realtime classes `@immutable` for all classes that do not require mutability
* Making fields in realtime classes `final` and `const` where possible
* Unifying realtime constructors with the rest of SDK, by making them use named parameters with `required` annotations
These changes are non-breaking, since all components with altered with breaking changes are only used internally, so no user action is needed to migrate
=> Named parameters and immutable fields for realtime classes

android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java, ios/Classes/codec/AblyFlutterReader.m
This should close https://github.com/ably/ably-flutter/issues/108. I've found out that this feature was implemented on Dart side, but it wasn't implemented in iOS and Android bridges, probably because of differences in implementation of these methods for each platform (iOS requires `NSDictionary` and Android requires `Param[]` array).  I've implemented bridges on each platform and now it seems to work fine 🙂
=> TransportParams support in ClientOptions

README.md, UPDATING.md, example/lib/ui/rest_sliver.dart, lib/src/common/common.dart, lib/src/common/src/history_direction.dart, lib/src/platform/src/codec.dart, lib/src/realtime/src/realtime_history_params.dart, lib/src/rest/src/rest_history_params.dart, test_integration/lib/test/realtime/realtime_encrypted_publish_test.dart, test_integration/lib/test/realtime/realtime_history_test.dart, test_integration/lib/test/realtime/realtime_presence_history_test.dart, test_integration/lib/test/realtime/realtime_publish_test.dart, test_integration/lib/test/rest/rest_encrypted_publish_test.dart, test_integration/lib/test/rest/rest_history_test.dart, test_integration/lib/test/rest/rest_presence_history_test.dart, test_integration/lib/test/rest/rest_publish_test.dart
This PR should resolve https://github.com/ably/ably-flutter/issues/83. I've replaced previously used `String` value with an enum shared between `RealtimeHistoryParams` and `RestHistoryParams`. Sadly, this is a breaking change, because it's not possible to deprecate unnamed constructors in Dart, but since it's a rather small difference, I don't think it should cause too many issues. I've left a note about this in UPDATING file.
=> Enum for Direction parameter in History

android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java, android/src/main/java/io/ably/flutter/plugin/generated/PlatformConstants.java, bin/codegen_context.dart, ios/Classes/codec/AblyFlutterReader.m, ios/Classes/codec/AblyPlatformConstants.h, ios/Classes/codec/AblyPlatformConstants.m, lib/src/generated/platform_constants.dart, lib/src/platform/src/codec.dart, lib/src/platform/src/info.dart, test/platform/info_test.dart, test/test_constants.dart
This should resolve https://github.com/ably/ably-flutter/issues/286, but will only work after https://github.com/ably/ably-common/pull/143 is landed. It's a simple change, that passes Dart runtime along with `ClientOptions` and encodes it as an `agent` header in platform implementations. The entire header looks like this:
```
Ably-Agent: ably-java/1.2.11 dart/2.16.2 ably-flutter/1.2.13 android/31
```
=> Dart runtime version as agent header

CHANGELOG.md, README.md, lib/src/platform/src/realtime/realtime.dart, lib/src/platform/src/rest/rest.dart, lib/src/platform/src/rest/rest_channels.dart, lib/src/push_notifications/src/local_device.dart, lib/src/push_notifications/src/push_channel.dart
This should resolve #368. Following information I got, I've updated all URLs in the documentation to use `ably.com/docs` instead of `ably.io/documentation`. I've also updated all `client-lib-development-guide` URLs from `docs.ably.io` to `docs.ably.com`
=> Updated documentation URLs

ios/Classes/handlers/CryptoHandlers.swift
I've made a small regression when merging https://github.com/ably/ably-flutter/pull/371 and this PR should fix it. One of the methods in `Crypto` was not updated, causing errors with crypto key generation. It wasn't identified in tests, since I just recently added tests for `Crypto` module in https://github.com/ably/ably-flutter/pull/372.
=> Fixed argument error in Swift implementation of Crypto.generateRandomKey

ios/Classes/handlers/PushHandlers.swift
This should solve https://github.com/ably/ably-flutter/issues/347. Apparently, for some combinations of Swift/XCode versions the compiler doesn't correctly recognize the `let guard` statements, which leads to `handle` and `channelName` being identified as nullable types, although they are guarded by specific checks before they are used. I've made a non-nullable, unwrapped versions of those variables to avoid those compilation errors.
=> Fixed iOS push module compilation issue on some versions of XCode

.github/workflows/check.yaml, analysis_options.yaml, lib/src/platform/src/push_activation_events_internal.dart, lib/src/platform/src/realtime/realtime.dart
This is the finishing touch for https://github.com/ably/ably-flutter/issues/278. Changes in this PR:
* Introduce lint rules to raise errors on missing returns and required params
* Ignore same-package deprecated library members to avoid failures when we deprecate a component of Ably library
* Cleanup and sort of anlysis rules with some additional checks included
* Temporary silenced `close_sink` rule for one of push module files ( related to https://github.com/ably/ably-flutter/issues/382)
* Updated GitHub action to fail if `flutter analyze` fails
=> Enabling CI lint checks

ios/Classes/codec/encoders/PushNotificationEncoders.swift, lib/src/platform/src/codec.dart, lib/src/push_notifications/src/ios_notification_settings.dart
This should close https://github.com/ably/ably-flutter/issues/389. I've implemented support for additional notification param introduced in iOS 15.
I haven't foud anything else that we should do for iOS 15 compatibility.
=> Added support for iOS 15 notification scheduledDeliverySettings

test_integration/lib/config/test_factory.dart, test_integration/lib/config/test_names.dart, test_integration/lib/test/realtime/realtime_history_with_auth_callback_test.dart, test_integration/lib/test/rest/rest_history_with_auth_callback_test.dart, test_integration/test_driver/test_implementation/realtime_tests.dart, test_integration/test_driver/test_implementation/rest_tests.dart, test_integration/test_driver/tests_config.dart
This should close https://github.com/ably/ably-flutter/issues/87. I've added new tests to cover the cases of fetching history when AuthCallback is used in `ClientOptions`
=> Integration tests for History with AuthCallback

android/build.gradle
This should close #385. The `ably-java` update only contains bugfixes, so it shouldn't affect Flutter SDK in any way.
=> Updated ably-java to 1.2.12

.github/workflows/docs.yml
It's not secret information, but makes it easier to migrate resources to a different AWS account in the future (something we'll likely be doing soon).
=> Use a secret to reference the AWS SDK account ID

.github/workflows/check.yaml, .github/workflows/docs.yml, .github/workflows/flutter_integration.yaml, lib/src/platform/src/platform_object.dart, lib/src/platform/src/streams_channel.dart, lib/src/push_notifications/src/push.dart
Since `ably-flutter` is ready to be used with Flutter 3, I've updated the CI workflows to use stable Flutter versions 3.0.x. This is also a blocker for #401 because latest versions of `test` dependency requires Flutter 3 to run. I've also updated the formatting of YAML files to increase consistency
=> Set Flutter CI version to ^3.0.0

.pubignore
This should close https://github.com/ably/ably-flutter/issues/400. I've added a `.pubignore` file to skip `test` and `integration_test` packages when publishing to pub.dev. This was the easiest way to resolve the problem mentioned in https://github.com/ably/ably-flutter/issues/400#issuecomment-1129236627, and pub.dev doesn't really give us any benefit for publishing the package with test suite included.
=> Added .pubignore to disable publishing tests to pub.dev

android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java, android/src/main/java/io/ably/flutter/plugin/types/SerializationException.java
This closes https://github.com/ably/ably-flutter/issues/149. Previously, serialization of enums and values without assigned encoder/decoder failed silently, returning `null` when proper value was not found. I've replaced these `null` returns with thrown exceptions, so it's clear that an error has occurred, and should be fixed
=> Replaced silent serialization errors with exceptions

CHANGELOG.md
The version bump and all changes were made in #393 but the release failed, due to Flutter 3 issues. This PR only updates the CHANGELOG file to include latest changes.
=> Release 1.2.14 (patch to original release PR)

.github/workflows/flutter_integration.yaml
This should fix https://github.com/ably/ably-flutter/issues/417. Updated version of `setup-java` step to `v3` and changed JDK used for Android from 1.8 to 11 (release from Temurin OpenJDK builds)
=> Updated Android CI to Java 11

lib/src/platform/src/codec.dart, test/models/client_options.dart
This should close https://github.com/ably/ably-flutter/issues/416. Altrought we're using the deprecated fields only inside `ably_flutter` package, the lint still produces an error on pub.dev, so we have to ignore those manually.
=> Added lint ignore on deprecated fields

.github/workflows/docs.yml
This should close https://github.com/ably/ably-flutter/issues/410. I've replaced the `dartdoc` usage as an external package with `dart doc` tool, which is now a part of Dart SDK.
=> Replaced old dartdoc usage with new doc tool

ios/Classes/AblyFlutter.m
Added fix for running `didFinishLaunchingWithOptions` in other registered plugins like uni_links.
Problem:
Since `didFinishLaunchingWithOptions` was returning NO, other plugins such as `uni_links`, also get the `initialAppLink` from `didFinishLaunchingWithOptions` were not able to run the function. This resulted in initialAppLink being `null` always.
=> Fix for running didFinishLaunchingWithOptions

android/build.gradle
As was suggested by @QuintinWillison - I've updated the ably-android dependency to the 1.2.14 version (Readme for [ably-java](https://github.com/ably/ably-java) says that the `io.ably:ably-android:1.2.15` should be available, but it looks like it has not been deployed yet).
=> Update ably-android to 1.2.14

lib/src/error/src/ably_exception.dart
Exposing full 'ErrorInfo' contents in 'AblyException.toString()' primarily to expose 'href'
Resolves #441
=> Expose error info in AblyException toString

android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java
Fixes issue described here: https://github.com/ably/ably-flutter/issues/461
=> Add numbers strategy for Gson to prevent changing int to double

android/build.gradle, ios/Classes/codec/AblyFlutterReader.m, test_integration/lib/config/test_factory.dart, test_integration/lib/config/test_names.dart, test_integration/lib/test/realtime/realtime_auth_url_test.dart, test_integration/test_driver/test_implementation/realtime_tests.dart
`authUrl` was being read as string which wasn't treated as an error as type mismatch is allowed in Objective C. 
This PR fixes this using authURL as NSURL
Also it turned out that ably-java didn't like `authUrl` having token as query string parameter. That's why I made a change on ably-java and upgraded its version here 
Fixes https://github.com/ably/ably-flutter/issues/465
=> Read authUrl as NSURL

android/build.gradle, android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java, android/src/main/java/io/ably/flutter/plugin/generated/PlatformConstants.java, example/android/build.gradle, example/pubspec.yaml
=> [SDK-3701] Fix/missing client options android decoder

.github/workflows/flutter_integration.yaml, android/build.gradle
Resolves https://github.com/ably/ably-flutter/issues/483
Jira link: [SDK-3871](https://ably.atlassian.net/browse/SDK-3871)
Bump the `ably-android` dependency to 1.2.32
[SDK-3871]: https://ably.atlassian.net/browse/SDK-3871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: concurrent encryption exception for Android

android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java
Resolves #461 
Fixes an issue where json decoding was inconsistent between underlying platforms (ios/android)
Note this change was already made and approved in #462 but the changes in the commit were subsequently overwritten in error during a merge conflict resolution.
=> fix: add numbers strategy for Gson to prevent changing int to double

android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java
* Mute `IllegalStateException` during `result.success` call
* Log method that throws it
=> fix: prevent app crash during method channel call

lib/src/platform/src/background_android_isolate_platform.dart, lib/src/platform/src/method_call_handler.dart, lib/src/platform/src/push_notification_events_internal.dart, lib/src/push_notifications/src/push_notification_events.dart
Copied https://github.com/ably/ably-flutter/pull/498
=> feat: setOnBackgroundMessage() is now a Future<void> that will await for the function to complete.

android/src/main/java/io/ably/flutter/plugin/AblyEventStreamHandler.java, android/src/main/java/io/ably/flutter/plugin/AblyMessageCodec.java, android/src/main/java/io/ably/flutter/plugin/dto/EnrichedConnectionStateChange.java, android/src/main/java/io/ably/flutter/plugin/generated/PlatformConstants.java, example/lib/ui/realtime_sliver.dart, ios/Classes/AblyFlutterStreamHandler.h, ios/Classes/AblyFlutterStreamHandler.m, ios/Classes/codec/AblyFlutterWriter.m, ios/Classes/codec/AblyPlatformConstants.h, ios/Classes/codec/AblyPlatformConstants.m, lib/src/generated/platform_constants.dart, lib/src/platform/src/codec.dart, lib/src/platform/src/realtime/connection.dart, lib/src/realtime/src/connection_state_change.dart
Resolves https://github.com/ably/ably-flutter/issues/502
Jira issue [ECO-4629](https://ably.atlassian.net/browse/ECO-4629) 
Add `key` and `id` to `ConnectionStateChange` event, updated example app
[ECO-4629]: https://ably.atlassian.net/browse/ECO-4629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ECO-4629] fix: propagate id and key fields for connection object for Android and iOS

example/ios/Podfile.lock, ios/Resources/PrivacyInfo.xcprivacy, ios/ably_flutter.podspec, test_integration/ios/Podfile.lock
- Includes the same changes from our ably-cocoa repo [here](https://github.com/ably/ably-cocoa/pull/1900)
- Bumps cocoa dependency to v1.2.30
=> [ECO-4748] Adds privacy manifest for iOS plugin

lib/src/message/src/message_extras.dart
Resolves https://github.com/ably/ably-flutter/issues/523
By default `JsonObject` is deserializing into `Map<Object?, Object?>`, we need to do explicit cast to get `Map<String, dynamic>`
=> [ECO-4807] fix: message extras decoding

ios/Classes/codec/AblyFlutterReader.h, ios/Classes/codec/AblyFlutterReader.m
Resolves https://github.com/ably/ably-flutter/issues/527
Fixed `transportParams` serialization logic, it returned `NSDictionary` with `NSString` values instead of `ARTStringifiable`.
=> fix(iOS): `transportParams` serialization

lib/src/push_notifications/src/notification.dart
Resolves https://github.com/ably/ably-flutter/issues/532
made `title` optional according to [FCM docs](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage.Notification)
=> fix: serialization for push notification

lib/src/platform/src/streams_channel.dart
Resolves https://github.com/ably/ably-flutter/issues/531
Makes `StreamsChannel#_lastId` field static, because:
During hot reloading, the Ably instance can be recreated. `StreamsChannel#_lastId` field is used to create IDs for platform-specific subscriptions, which are used on iOS and Android. Code that used to register subscription handler is a singleton, so two Ably instances overwrite each other, causing the platform implementation to be out of sync with the Flutter message handler.
=> [ECO-4875] fix: out of sync message handlers
